import { createHash } from 'node:crypto';
import {
  cpSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  rmSync,
  statSync,
  writeFileSync,
} from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { build } from 'esbuild';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const OUTPUT = resolve(ROOT, 'build/v1');
const CLIENT = resolve(ROOT, 'src/app/client');
const APPS_SCRIPT = resolve(ROOT, 'appsscript');
const COMPATIBILITY_BANNER = `if(typeof Promise.withResolvers!=="function"){Promise.withResolvers=function(){let resolve,reject;const promise=new Promise((nextResolve,nextReject)=>{resolve=nextResolve;reject=nextReject});return{promise,resolve,reject}}}`;

function sha256(value) {
  return createHash('sha256').update(value).digest('hex');
}

function read(path) {
  return readFileSync(resolve(ROOT, path), 'utf8');
}

function scriptSafe(value) {
  return value
    .replaceAll('</script', '<\\/script')
    .replaceAll('\u2028', '\\u2028')
    .replaceAll('\u2029', '\\u2029');
}

async function bundle(entryPoint, globalName) {
  const result = await build({
    entryPoints: [resolve(CLIENT, entryPoint)],
    bundle: true,
    format: 'iife',
    globalName,
    platform: 'browser',
    target: ['chrome110', 'safari16'],
    minify: true,
    legalComments: 'none',
    sourcemap: false,
    write: false,
    metafile: true,
    logLevel: 'warning',
    banner: { js: COMPATIBILITY_BANNER },
  });
  const imports = Object.values(result.metafile.outputs).flatMap(output => output.imports);
  if (imports.length > 0) {
    throw new Error(`${entryPoint} has external imports: ${JSON.stringify(imports)}`);
  }
  const code = result.outputFiles[0].text;
  if (/sourceMappingURL/i.test(code)) throw new Error(`${entryPoint} contains a source-map reference.`);
  return code;
}

function inlineHtml(template, css, javascript, { production }) {
  let html = template
    .replace(/\s*<link rel="stylesheet" href="\.\/styles\.css">\s*/u, '\n')
    .replace(/\s*<script type="module" src="\.\/(?:main|local-main)\.mjs"><\/script>\s*/u, '\n');
  const bootstrap = production
    ? '<script>globalThis.__NYU_VPAT_BOOTSTRAP__ = <?!= bootstrapJson ?>;</script>\n'
    : '';
  html = html.replace('</head>', `  <style>${scriptSafe(css)}</style>\n  </head>`);
  html = html.replace('</body>', `  ${bootstrap}<script>${scriptSafe(javascript)}</script>\n  </body>`);
  if (/(?:src|href)=["']\.\//u.test(html)) throw new Error('The inline V1 artifact retained a relative asset.');
  return html;
}

rmSync(OUTPUT, { recursive: true, force: true });
mkdirSync(OUTPUT, { recursive: true });

const [productionBundle, localBundle] = await Promise.all([
  bundle('main.mjs', 'NyuVpatAnalyzerProduction'),
  bundle('local-main.mjs', 'NyuVpatAnalyzerPreview'),
]);
const css = read('src/app/client/styles.css');
const productionHtml = inlineHtml(read('src/app/client/index.html'), css, productionBundle, {
  production: true,
});
const localHtml = inlineHtml(read('src/app/client/local.html'), css, localBundle, {
  production: false,
});

writeFileSync(resolve(OUTPUT, 'Index.html'), productionHtml);
writeFileSync(resolve(OUTPUT, 'local.html'), localHtml);

const copiedAppsScript = [];
for (const name of readdirSync(APPS_SCRIPT).sort()) {
  if (!name.endsWith('.gs') && name !== 'appsscript.json') continue;
  cpSync(resolve(APPS_SCRIPT, name), resolve(OUTPUT, name));
  copiedAppsScript.push(name);
}

const providerContractSource = [
  '// Generated by scripts/build-v1-app.mjs from versioned repository contracts.',
  `var VPAT_CONFORMANCE_SYSTEM_PROMPT_ = ${JSON.stringify(read('prompts/conformance-analysis.v1.md'))};`,
  `var VPAT_QUALITY_SYSTEM_PROMPT_ = ${JSON.stringify(read('prompts/quality-analysis.v1.md'))};`,
  `var VPAT_WCAG_CATALOG_ = Object.freeze(${read('config/vpat-2.5-wcag-criteria.v1.json').trim()});`,
  `var VPAT_QUALITY_RUBRIC_ = Object.freeze(${read('config/quality-rubric.v1.json').trim()});`,
  `var VPAT_SCORING_RULES_ = Object.freeze(${read('config/scoring-rules.v1.json').trim()});`,
  '',
].join('\n');
writeFileSync(resolve(OUTPUT, 'ProviderContractData.gs'), providerContractSource);
copiedAppsScript.push('ProviderContractData.gs');

const files = readdirSync(OUTPUT)
  .filter(name => name !== 'build-manifest.json')
  .sort()
  .map(name => {
    const bytes = readFileSync(resolve(OUTPUT, name));
    return { name, bytes: statSync(resolve(OUTPUT, name)).size, sha256: sha256(bytes) };
  });
const manifest = {
  schemaVersion: '1.0.0',
  id: 'nyu-vpat-analyzer-v1-local-build',
  buildSha256: sha256(JSON.stringify(files)),
  target: ['chrome110', 'safari16'],
  design: { direction: 'Document Workbench', revision: 9 },
  webReviewViews: ['Summary', 'WCAG criteria', 'Report quality'],
  exportedSheetTabs: [
    'Overview',
    'Line-item Review',
    'Quality Requirements',
    'Scoring',
    'Methodology & disclaimer',
  ],
  productionEntrypoint: 'Index.html',
  localPreviewEntrypoint: 'local.html',
  appsScriptFiles: copiedAppsScript,
  files,
};
writeFileSync(resolve(OUTPUT, 'build-manifest.json'), `${JSON.stringify(manifest, null, 2)}\n`);

console.log(
  `built V1 app: ${productionBundle.length.toLocaleString()} production JS bytes, ` +
    `${localBundle.length.toLocaleString()} preview JS bytes, ${files.length} files`,
);
